successMessage: 多个副本被调度
failureMessage: 只有一个副本被调度
category: Reliability
target: Controller
controllers:
  include:
  - Deployment
schema:
  '$schema': http://json-schema.org/draft-07/schema
  type: object
  required:
  - spec
  properties:
    spec:
      type: object
      required:
      - replicas
      properties:
        replicas:
          type: integer
          minimum: 2
mutations:
  - op: add
    path: /spec/replicas
    value: 3